/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inatelmarket;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author André Luiz
 */
public class Tela extends javax.swing.JFrame {

    ArrayList<Produto> array = new ArrayList<Produto>();
    Arquivo arquivo = new Arquivo();
    int pos = 0;
    Produto p1 = new Produto();

    /**
     * Creates new form Tela
     */
    public Tela() {

        initComponents();
        cupomTextArea.append("=================\n");
        cupomTextArea.append("Cupom\n\n");
        this.setSize(880, 650);
    }

    float total = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        frutas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb2 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        padaria = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb18 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb20 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        açougue = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb14 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        legumes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb26 = new javax.swing.JCheckBox();
        cb28 = new javax.swing.JCheckBox();
        cb30 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        preço = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pagarButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Nota = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cupomTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jCheckBox3.setText("jCheckBox2");

        jCheckBox18.setText("Banana ");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });

        jCheckBox19.setText("Maça   ");

        jCheckBox20.setText("Pera ");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });

        jCheckBox21.setText("Manga");

        jCheckBox22.setText("Morango");

        jCheckBox23.setText("Pessego");

        jCheckBox24.setText("Uva");

        jCheckBox25.setText("Mamão");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        titulo.setBackground(new java.awt.Color(23, 35, 51));
        titulo.setPreferredSize(new java.awt.Dimension(100, 600));

        jLabel1.setBackground(new java.awt.Color(23, 35, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUTOS");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        frutas.setBackground(new java.awt.Color(120, 168, 252));
        frutas.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("POPULARES");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        cb2.setText("SKOL");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb6.setText("BRAHMA");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb4.setText("ORIGINAL");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        cb8.setText("SERRA MALTE");
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frutasLayout = new javax.swing.GroupLayout(frutas);
        frutas.setLayout(frutasLayout);
        frutasLayout.setHorizontalGroup(
            frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb4)
                    .addComponent(jLabel2)
                    .addComponent(cb2))
                .addGap(58, 58, 58)
                .addGroup(frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frutasLayout.createSequentialGroup()
                        .addComponent(cb6)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frutasLayout.setVerticalGroup(
            frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frutasLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2)
                    .addComponent(cb6))
                .addGap(23, 23, 23)
                .addGroup(frutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb4)
                    .addComponent(cb8)))
            .addGroup(frutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        padaria.setBackground(new java.awt.Color(120, 168, 252));
        padaria.setPreferredSize(new java.awt.Dimension(300, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IPA");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        cb18.setText("IMPERIAL");
        cb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb18ActionPerformed(evt);
            }
        });

        cb24.setText("COLORADO");
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });

        cb20.setText("BADEN BADEN");
        cb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb20ActionPerformed(evt);
            }
        });

        cb22.setText("HOEGARDEN");
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout padariaLayout = new javax.swing.GroupLayout(padaria);
        padaria.setLayout(padariaLayout);
        padariaLayout.setHorizontalGroup(
            padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(padariaLayout.createSequentialGroup()
                        .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb20)
                            .addComponent(cb18))
                        .addGap(33, 33, 33)
                        .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(padariaLayout.createSequentialGroup()
                                .addComponent(cb22)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb24)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        padariaLayout.setVerticalGroup(
            padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padariaLayout.createSequentialGroup()
                .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(padariaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb18)
                            .addComponent(cb22))
                        .addGap(23, 23, 23)
                        .addGroup(padariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb20)
                            .addComponent(cb24)))
                    .addGroup(padariaLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        açougue.setBackground(new java.awt.Color(120, 168, 252));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LARGER");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        cb14.setText("ESTRELA GALICIA");
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });

        cb12.setText("STELLA ARTOIS");
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });

        cb10.setText("HIENEKEN");
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });

        cb16.setText("BECKS");
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout açougueLayout = new javax.swing.GroupLayout(açougue);
        açougue.setLayout(açougueLayout);
        açougueLayout.setHorizontalGroup(
            açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(açougueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(açougueLayout.createSequentialGroup()
                        .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb10)
                            .addComponent(jLabel5))
                        .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(açougueLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(açougueLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(cb14)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(açougueLayout.createSequentialGroup()
                        .addComponent(cb12)
                        .addGap(18, 18, 18)
                        .addComponent(cb16)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        açougueLayout.setVerticalGroup(
            açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(açougueLayout.createSequentialGroup()
                .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(açougueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(açougueLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb10)
                            .addComponent(cb14))
                        .addGap(23, 23, 23)
                        .addGroup(açougueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb12)
                            .addComponent(cb16))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        legumes.setBackground(new java.awt.Color(120, 168, 252));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PILSEN");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        cb26.setText("WALLS");
        cb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb26ActionPerformed(evt);
            }
        });

        cb28.setText("EISENBAH");
        cb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb28ActionPerformed(evt);
            }
        });

        cb30.setText("BUDWAISER");
        cb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb30ActionPerformed(evt);
            }
        });

        cb32.setText("CORONA");
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout legumesLayout = new javax.swing.GroupLayout(legumes);
        legumes.setLayout(legumesLayout);
        legumesLayout.setHorizontalGroup(
            legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(legumesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cb26)
                    .addComponent(cb28))
                .addGroup(legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(legumesLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(legumesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb30)
                            .addComponent(cb32))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        legumesLayout.setVerticalGroup(
            legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(legumesLayout.createSequentialGroup()
                .addGroup(legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(legumesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb30))
                    .addGroup(legumesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(cb26)
                        .addGap(23, 23, 23)
                        .addGroup(legumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb28)
                            .addComponent(cb32))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Preço total:");

        jButton7.setText("Limpar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Nota");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        pagarButton.setText("FINALIZAR");
        pagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout preçoLayout = new javax.swing.GroupLayout(preço);
        preço.setLayout(preçoLayout);
        preçoLayout.setHorizontalGroup(
            preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(preçoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(preçoLayout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pagarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        preçoLayout.setVerticalGroup(
            preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preçoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preçoLayout.createSequentialGroup()
                        .addComponent(pagarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(preçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        cupomTextArea.setColumns(20);
        cupomTextArea.setRows(5);
        jScrollPane2.setViewportView(cupomTextArea);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("  CERVEJARIA GGF\n   CUPOM FISCAL\nAV CORONEL JOAO .030\nCENTRO,OSASCO ,SP \n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout NotaLayout = new javax.swing.GroupLayout(Nota);
        Nota.setLayout(NotaLayout);
        NotaLayout.setHorizontalGroup(
            NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(NotaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NotaLayout.setVerticalGroup(
            NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(padaria, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frutas, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(legumes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(açougue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(preço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(frutas, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(açougue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(padaria, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(legumes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(preço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        Cupons c1 = new Cupons();

        c1.setVisible(true);
        
        
        c1.setDefaultCloseOperation(c1.DISPOSE_ON_CLOSE);
        //FECHA APENAS O CUPOM
        //*


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        total = (float) 0.00;
        priceLabel.setText("0.00");
        
        cb2.setSelected(false);
        
        cb4.setSelected(false);
       
        cb6.setSelected(false);
        
        cb8.setSelected(false);
        
        cb10.setSelected(false);
        
        cb12.setSelected(false);
      
        cb14.setSelected(false);
       
        cb16.setSelected(false);
        
        cb18.setSelected(false);
      
        cb20.setSelected(false);

        cb22.setSelected(false);
       
        cb24.setSelected(false);
       
        cb26.setSelected(false);
     
        cb28.setSelected(false);

        cb30.setSelected(false);
   
        cb32.setSelected(false);

        
        cupomTextArea.setText("");
        cupomTextArea.append("=================\n");
        cupomTextArea.append("Cupom\n\n");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void cb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb18ActionPerformed
        // TODO add your handling code here:
        if (cb18.isSelected()) {

            total = (float) (total + 6.8);
            cupomTextArea.append("IMPERIAL \n600ML GARRAFA \nT.A.=6,4% \n- R$6,8O\n-------------\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb18ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb22ActionPerformed

    private void cb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb28ActionPerformed
        // TODO add your handling code here:
        if (cb28.isSelected()) {

            total = (float) (total + 1.70);
            cupomTextArea.append("Alface R$1.70\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb28ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
        if (cb4.isSelected()) {
            total = (float) (total + 3.50);
            cupomTextArea.append("ORIGINAL \n600ML GARRAFA \nT.A.=4,2% \n- R$3,5O\n-------------\n");
            calculaTotal();
        }
    }//GEN-LAST:event_cb4ActionPerformed

    private void pagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtonActionPerformed

        cupomTextArea.append("Total: " + total + "\n");
        cupomTextArea.append("=================\n");

        if(total!=0){
            String cupom = cupomTextArea.getText();
            p1.cupomProduto = cupom;
            array.add(p1);
            arquivo.salvar(array);
            pos++;
            JOptionPane.showMessageDialog(null, "COMPRA FINALIZADA xD");
        }
        else if(total==0){
            JOptionPane.showMessageDialog(null, "PARECE QUE VOCE NAO COMPROU NADA :(");
        }
        

        total = 0;

        total = (float) 0.00;
        priceLabel.setText("0.00");
     
        cb2.setSelected(false);
     
        cb4.setSelected(false);
        
        cb6.setSelected(false);
        
        cb8.setSelected(false);
        
        cb10.setSelected(false);
       
        cb12.setSelected(false);
       
        cb14.setSelected(false);
        
        cb16.setSelected(false);
      
        cb18.setSelected(false);
       
        cb20.setSelected(false);
      
        cb22.setSelected(false);

        cb24.setSelected(false);

        cb26.setSelected(false);

        cb28.setSelected(false);

        cb30.setSelected(false);
   
        cb32.setSelected(false);

        cupomTextArea.setText("");
        cupomTextArea.append("=================\n");
        cupomTextArea.append("Cupom\n\n");


    }//GEN-LAST:event_pagarButtonActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        if (cb2.isSelected()) {
            total = (float) (total + 1.99);
            cupomTextArea.append("SKOL \n350ML LATA \nT.A.=3,8% \n- R$1,99\n-------------\n");
            calculaTotal();
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
        if (cb6.isSelected()) {
            total = (float) (total + 1.80);
            cupomTextArea.append("BRAHMA \n350ML LATA \nT.A.=4% \n- R$1,80\n-------------\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
        // TODO add your handling code here:
        if (cb8.isSelected()) {
            total = (float) (total + 5);
            cupomTextArea.append("SERRA MALTE \n600ML GARRAFA \nT.A.=4% \n- R$5,OO\n-------------\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb20ActionPerformed
        // TODO add your handling code here:
        if (cb20.isSelected()) {

            total = (float) (total + 4);
            cupomTextArea.append("Torta Holandesa R$4.00\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb20ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
        // TODO add your handling code here:
        if (cb24.isSelected()) {

            total = (float) (total + 8);
            cupomTextArea.append("COLORADO \n600ML GARRAFA \nT.A.=7% \n- R$8,OO\n-------------\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        // TODO add your handling code here:
        if (cb10.isSelected()) {

            total = (float) (total + 35);
            cupomTextArea.append("Alcatra R$35.00\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb10ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        // TODO add your handling code here:
        if (cb12.isSelected()) {

            total = (float) (total + 29);
            cupomTextArea.append("Contra File R$29.00\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
        // TODO add your handling code here:
        if (cb14.isSelected()) {

            total = (float) (total + 14);
            cupomTextArea.append("Coxinha de Frango R$14.00\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb16ActionPerformed

    private void cb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb26ActionPerformed
        // TODO add your handling code here:
        if (cb26.isSelected()) {

            total = (float) (total + 1.30);
            cupomTextArea.append("Cenoura R$1.30\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb26ActionPerformed

    private void cb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb30ActionPerformed
        // TODO add your handling code here:
        if (cb30.isSelected()) {

            total = (float) (total + 2.50);
            cupomTextArea.append("Beringela R$2.50\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb30ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
        // TODO add your handling code here:
        if (cb32.isSelected()) {

            total = (float) (total + 1.90);
            cupomTextArea.append("Cebola R$1.90\n");
            calculaTotal();

        }
    }//GEN-LAST:event_cb32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nota;
    private javax.swing.JPanel açougue;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb18;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb20;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb28;
    private javax.swing.JCheckBox cb30;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JTextArea cupomTextArea;
    private javax.swing.JPanel frutas;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel legumes;
    private javax.swing.JPanel padaria;
    private javax.swing.JButton pagarButton;
    private javax.swing.JPanel preço;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables

    private void calculaTotal() {

        priceLabel.setText("" + total);

    }
    public void desativa(float valor){
        
    }

}
